### PR TITLE
Files and folder structure housekeeping #12

### PR DESCRIPTION
**Pull request by ake123**
Files and folder structure housekeeping #12

### CODE REVIEW

**Comment by pitkant** [comment]
Hi, thanks for the PR. I noticed you had moved `full_fennica_fields` folder to `old`. `full_fennica_fields` is a WIP folder that should be left at the "root" folder of `inst/examples`: please re-check that files and folders that have been recently worked on are not among files moved to `old`.

**Comment by pitkant** [comment]
I reviewed the `inst/examples` folder and there were still some files that were clearly outdated, last changes were 7 years ago or so. 

Could you please look through these and move unnecessary files to `inst/examples/old` IF they are not used in any current .Rmd files or scripts. For example publishers-up-to-1828.csv and publishers.csv might be something that were generated with old scripts but without closer scrutiny it's hard to say if they are used in some .Rmd files.

**Comment by ake123** [comment]
Yes I fixed all. Do we need the old .png files?

**Comment by ake123** [comment]
Cleaned all the files!

**Comment by pitkant** [comment]
Ok, thank you for the work

**Pull request merged**
